### PR TITLE
update dehydrated to 0.5.0

### PR DESCRIPTION
**Pull request by stenius**

### CODE REVIEW

**Comment by tjcelaya** [comment]
Thanks for the PR but it would make more sense to open it against [autopilotpattern/nginx](https://github.com/autopilotpattern/nginx). We'll get it merged there once we've had a chance to test.

**Comment by tjcelaya** [comment]
I'll test this fix and prefer it over autopilotpattern/nginx#56 if it works as expected. My decision to set the LICENSE url in the configs in that PR was based on uncertainty about the following comment in [dehydrated 0.4.0](https://github.com/lukas2511/dehydrated/releases/tag/v0.4.0):

> dehydrated now asks you to read and accept the CAs terms of service before creating an account

**Comment by stenius** [comment]
I already had an account so o haven't tested that flow yet. I set the
private account key in consul

**Comment by tjcelaya** [comment]
Mind if I cherry-pick your commit into a PR on autopilotpattern/nginx or do you want to open the PR yourself?

**Comment by stenius** [comment]
@tjcelaya not at all.  It'd be awesome if you got this code in the main repo.

**Pull request closed without merging**
